# Config file for automatic testing at travis-ci.org

language: python

python: "2.7"

git:
  submodules: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib pytest

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py test

# command to run tests, e.g. python setup.py test
script: travis_retry py.test

notifications:
  email: false
